/* SHARED CONSTANTS */
export const CLEAR_STORE = 'CLEAR_STORE';

/* BOARD CONSTANTS */

export const RECEIVE_BOARD = 'RECEIVE_BOARD';
export const RECEIVE_BOARDS = 'RECEIVE_BOARDS';
export const ADD_NEW_BOARD = 'ADD_NEW_BOARD';
export const RECEIVE_BOARD_NOTES = 'RECEIVE_BOARD_NOTES';

/* NOTE CONSTANTS */
export const SELECT_NOTE = 'SELECT_NOTE';
export const RECEIVE_NOTE = 'RECEIVE_NOTE';
export const RECEIVE_NOTES = 'RECEIVE_NOTES';

/* USER CONSTANTS */
export const SET_LOGIN_USER = 'SET_LOGIN_USER';
export const REMOVE_LOGIN_USER = 'REMOVE_LOGIN_USER';

/* NOTEBOARD CONSTANTS */
export const MOVE_NOTE = 'MOVE_NOTE';
/* ITEM TYPES FOR REACT DND*/
export const NOTE = 'note';

/* SOCKETS */
export const EMIT = 'EMIT';
export const CONNECT = 'CONNECT';
export const ADD_LISTENER = 'ADD_LISTENER';
export const REMOVE_LISTENER = 'REMOVE_LISTENER';
