/* SHARED CONSTANTS */
export const CLEAR_STORE = 'CLEAR_STORE';

/* BOARD CONSTANTS */
export const RECEIVE_BOARD = 'RECEIVE_BOARD';
export const RECEIVE_BOARDS = 'RECEIVE_BOARDS';
export const ADD_NEW_BOARD = 'ADD_NEW_BOARD';

/* NOTE CONSTANTS */
export const RECEIVE_NOTE = 'RECEIVE_NOTE';
export const RECEIVE_NOTES = 'RECEIVE_NOTES';

/* USER CONSTANTS */
export const SET_LOGIN_USER = 'SET_LOGIN_USER';
export const REMOVE_LOGIN_USER = 'REMOVE_LOGIN_USER';

